// playground/react-app/src/pages/account/preferences.tsx
import { useState } from 'react'
import { AccountLayout } from './layout.tsx'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'

interface PreferencesProps {
  appName?: string
  currentUser?: { id: number; name: string; email: string } | null
  navigate: (href: string) => void
  [key: string]: any
}

export default function Preferences({ appName, currentUser, navigate }: PreferencesProps) {
  const [theme, setTheme] = useState<'light' | 'dark' | 'system'>(() => {
    if (typeof localStorage === 'undefined') return 'system'
    return (localStorage.getItem('theme') as any) ?? 'system'
  })

  const applyTheme = (t: 'light' | 'dark' | 'system') => {
    setTheme(t)
    if (t === 'system') {
      localStorage.removeItem('theme')
      const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches
      document.documentElement.classList.toggle('dark', prefersDark)
    } else {
      localStorage.setItem('theme', t)
      document.documentElement.classList.toggle('dark', t === 'dark')
    }
  }

  const themes = [
    { value: 'light' as const, label: 'Light', description: 'A clean, bright appearance.' },
    { value: 'dark' as const, label: 'Dark', description: 'Easy on the eyes in low light.' },
    { value: 'system' as const, label: 'System', description: 'Follows your operating system setting.' },
  ]

  return (
    <AccountLayout appName={appName} currentUser={currentUser} navigate={navigate} activePath="/account/preferences">
      <div className="space-y-8">
        <div>
          <h3 className="text-lg font-medium">Preferences</h3>
          <p className="text-sm text-muted-foreground">
            Customize the appearance and behavior of the app.
          </p>
        </div>

        {/* Theme */}
        <div className="space-y-3">
          <Label>Theme</Label>
          <p className="text-sm text-muted-foreground">Select your preferred theme.</p>
          <div className="grid grid-cols-3 gap-3">
            {themes.map(t => (
              <button
                key={t.value}
                type="button"
                onClick={() => applyTheme(t.value)}
                className={`rounded-lg border p-4 text-left text-sm transition-colors hover:bg-accent ${
                  theme === t.value ? 'border-foreground' : 'border-border'
                }`}
              >
                <div className="font-medium">{t.label}</div>
                <div className="text-xs text-muted-foreground mt-1">{t.description}</div>
              </button>
            ))}
          </div>
        </div>

        {/* Language */}
        <div className="space-y-3">
          <Label>Language</Label>
          <p className="text-sm text-muted-foreground">Select the language for the interface.</p>
          <Button variant="outline" disabled className="justify-between w-48">
            English
            <span className="text-xs text-muted-foreground">Default</span>
          </Button>
        </div>
      </div>
    </AccountLayout>
  )
}

// examples/starter-vue/src/pages/account/preferences.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import AccountLayout from './layout.vue'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'

const props = withDefaults(defineProps<{
  appName?: string
  currentUser?: { name: string; email: string; role?: string } | null
  navigate: (href: string) => void
}>(), {
  appName: 'Mantiq',
})

const theme = ref<'light' | 'dark' | 'system'>('system')
const success = ref('')

onMounted(() => {
  const stored = localStorage.getItem('theme')
  if (stored === 'light' || stored === 'dark') {
    theme.value = stored
  } else {
    theme.value = 'system'
  }
})

function setTheme(value: 'light' | 'dark' | 'system') {
  theme.value = value
  if (value === 'system') {
    localStorage.removeItem('theme')
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches
    document.documentElement.classList.toggle('dark', prefersDark)
  } else {
    localStorage.setItem('theme', value)
    document.documentElement.classList.toggle('dark', value === 'dark')
  }
  success.value = 'Preferences saved.'
}
</script>

<template>
  <AccountLayout
    :app-name="appName"
    :current-user="currentUser"
    :navigate="navigate"
    active-path="/account/preferences"
    title="Settings"
    description="Manage your account settings."
  >
    <Card>
      <CardHeader>
        <CardTitle>Preferences</CardTitle>
        <CardDescription>Customize your experience.</CardDescription>
      </CardHeader>
      <CardContent>
        <div
          v-if="success"
          class="mb-4 rounded-md border border-green-500/30 bg-green-500/10 px-4 py-3 text-sm text-green-600 dark:text-green-400"
        >
          {{ success }}
        </div>
        <div class="space-y-4 max-w-md">
          <div class="space-y-2">
            <Label>Theme</Label>
            <div class="flex gap-2">
              <Button
                v-for="opt in (['light', 'dark', 'system'] as const)"
                :key="opt"
                :variant="theme === opt ? 'default' : 'outline'"
                size="sm"
                @click="setTheme(opt)"
              >
                {{ opt.charAt(0).toUpperCase() + opt.slice(1) }}
              </Button>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  </AccountLayout>
</template>
