// examples/starter-svelte/src/lib/components/layout/AuthenticatedLayout.svelte
<script lang="ts">
  import { post } from '$lib/api'
  import * as Sidebar from '$lib/components/ui/sidebar'
  import AppSidebar from './AppSidebar.svelte'
  import type { Snippet } from 'svelte'

  let {
    children,
    currentUser = null,
    appName = 'Mantiq',
    navigate,
    activePath,
  }: {
    children: Snippet
    currentUser?: { name: string; email: string; role?: string } | null
    appName?: string
    navigate: (href: string) => void
    activePath: string
  } = $props()

  const user = $derived(currentUser ?? { name: 'User', email: 'user@example.com' })

  async function handleLogout() {
    await post('/logout', {})
    navigate('/login')
  }
</script>

<Sidebar.Provider>
  <AppSidebar
    {user}
    {appName}
    {activePath}
    {navigate}
    onLogout={handleLogout}
  />
  <Sidebar.Inset>
    {@render children()}
  </Sidebar.Inset>
</Sidebar.Provider>

// studio-test/src/components/layout/authenticated-layout.tsx
import { useCallback } from 'react'
import { post } from '@/lib/api'
import { SidebarProvider, SidebarInset } from '@/components/ui/sidebar'
import { AppSidebar } from './app-sidebar'

interface AuthenticatedLayoutProps {
  children: React.ReactNode
  currentUser?: { name: string; email: string; role?: string } | null
  appName?: string
  navigate: (href: string) => void
  activePath: string
}

export function AuthenticatedLayout({
  children,
  currentUser,
  appName = 'Mantiq',
  navigate,
  activePath,
}: AuthenticatedLayoutProps) {
  const handleLogout = useCallback(async () => {
    await post('/logout', {})
    navigate('/login')
  }, [navigate])

  const user = currentUser ?? { name: 'User', email: 'user@example.com' }

  return (
    <SidebarProvider defaultOpen={true}>
      <AppSidebar
        user={user}
        appName={appName}
        activePath={activePath}
        navigate={navigate}
        onLogout={handleLogout}
      />
      <SidebarInset>
        {children}
      </SidebarInset>
    </SidebarProvider>
  )
}
