// examples/starter-svelte/src/pages/users/DeleteUserDialog.svelte
<script lang="ts">
  import * as Dialog from '$lib/components/ui/dialog'
  import { Button } from '$lib/components/ui/button'

  interface UserType {
    id: number
    name: string
    email: string
    status: string
    created_at: string
  }

  let {
    user = $bindable(null),
    onSuccess,
  }: {
    user: UserType | null
    onSuccess: () => void
  } = $props()

  let error = $state('')
  let submitting = $state(false)

  async function handleDelete() {
    if (!user) return
    submitting = true
    error = ''
    try {
      const res = await fetch(`/api/users/${user.id}`, {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
      })
      if (!res.ok) {
        const data = await res.json().catch(() => null)
        throw new Error(data?.message ?? `Request failed (${res.status})`)
      }
      user = null
      onSuccess()
    } catch (err: any) {
      error = err.message ?? 'Something went wrong'
    } finally {
      submitting = false
    }
  }
</script>

<Dialog.Root
  open={!!user}
  onOpenChange={(v) => { if (!v) { error = ''; user = null } }}
>
  <Dialog.Content>
    <Dialog.Header>
      <Dialog.Title>Are you sure?</Dialog.Title>
      <Dialog.Description>
        This will permanently delete <span class="font-medium text-foreground">{user?.name}</span>
        ({user?.email}). This action cannot be undone.
      </Dialog.Description>
    </Dialog.Header>

    {#if error}
      <p class="text-sm text-destructive">{error}</p>
    {/if}

    <Dialog.Footer>
      <Button type="button" variant="outline" onclick={() => user = null}>
        Cancel
      </Button>
      <Button
        type="button"
        variant="destructive"
        disabled={submitting}
        onclick={handleDelete}
      >
        {submitting ? 'Deleting...' : 'Delete'}
      </Button>
    </Dialog.Footer>
  </Dialog.Content>
</Dialog.Root>

// examples/starter-vue/src/pages/users/dialogs/DeleteUserDialog.vue
<script setup lang="ts">
import { ref } from 'vue'
import { api } from '@/lib/api'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'

const props = defineProps<{
  user: { id: number; name: string; email: string } | null
}>()

const open = defineModel<boolean>('open', { default: false })
const emit = defineEmits<{ deleted: [] }>()

const loading = ref(false)
const error = ref('')

async function handleDelete() {
  if (!props.user) return
  error.value = ''
  loading.value = true
  const { ok, data } = await api(`/api/users/${props.user.id}`, { method: 'DELETE' })
  loading.value = false
  if (ok) {
    open.value = false
    emit('deleted')
  } else {
    error.value = data?.error ?? 'Failed to delete user.'
  }
}
</script>

<template>
  <Dialog v-model:open="open">
    <DialogContent class="sm:max-w-[425px]">
      <DialogHeader>
        <DialogTitle>Delete User</DialogTitle>
        <DialogDescription>
          Are you sure you want to delete <strong>{{ user?.name }}</strong>? This action cannot be undone.
        </DialogDescription>
      </DialogHeader>
      <div
        v-if="error"
        class="rounded-md border border-destructive px-4 py-3 text-sm text-destructive"
      >
        {{ error }}
      </div>
      <DialogFooter>
        <Button type="button" variant="outline" @click="open = false">Cancel</Button>
        <Button variant="destructive" :disabled="loading" @click="handleDelete">
          {{ loading ? 'Deleting...' : 'Delete User' }}
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>
