// examples/kit-svelte/src/App.svelte
<script lang="ts">
  import { onMount, onDestroy, setContext } from 'svelte'

  export let pages: Record<string, any> = {}
  export let initialData: Record<string, any> = {}

  const windowData = typeof window !== 'undefined' ? (window as any).__MANTIQ_DATA__ : {}
  const initial = initialData ?? windowData

  let currentPage: string = initial._page ?? 'Login'
  let pageData: Record<string, any> = initial

  $: PageComponent = pages[currentPage] ?? null

  async function navigate(href: string) {
    const res = await fetch(href, {
      headers: { 'X-Mantiq': 'true', Accept: 'application/json' },
    })
    const newData = await res.json()
    currentPage = newData._page
    pageData = newData
    history.pushState(null, '', newData._url)
  }

  setContext('navigate', navigate)

  function handleClick(e: MouseEvent) {
    const anchor = (e.target as HTMLElement).closest('a')
    const href = anchor?.getAttribute('href')
    if (!href?.startsWith('/') || anchor?.target || e.ctrlKey || e.metaKey) return
    e.preventDefault()
    navigate(href)
  }

  function handlePop() { navigate(location.pathname) }

  onMount(() => {
    document.addEventListener('click', handleClick)
    window.addEventListener('popstate', handlePop)
  })

  onDestroy(() => {
    if (typeof window !== 'undefined') {
      document.removeEventListener('click', handleClick)
      window.removeEventListener('popstate', handlePop)
    }
  })
</script>

{#if PageComponent}
  <svelte:component this={PageComponent} {...pageData} {navigate} />
{/if}

// docs/src/App.tsx
import { useState, useCallback, useEffect } from 'react'

interface MantiqAppProps {
  pages: Record<string, React.ComponentType<any>>
  initialData?: Record<string, any>
}

export function MantiqApp({ pages, initialData }: MantiqAppProps) {
  const windowData = typeof window !== 'undefined' ? (window as any).__MANTIQ_DATA__ : {}
  const initial = initialData ?? windowData
  const [page, setPage] = useState<string>(initial._page ?? 'Home')
  const [data, setData] = useState<Record<string, any>>(initial)

  const navigate = useCallback(async (href: string) => {
    const res = await fetch(href, {
      headers: { 'X-Mantiq': 'true', Accept: 'application/json' },
    })
    const newData = await res.json()
    setPage(newData._page)
    setData(newData)
    history.pushState(null, '', newData._url)

    // Scroll to top on navigation
    window.scrollTo(0, 0)

    // Re-run Prism syntax highlighting after navigation
    requestAnimationFrame(() => {
      if (typeof (window as any).Prism !== 'undefined') {
        ;(window as any).Prism.highlightAll()
      }
    })
  }, [])

  useEffect(() => {
    const handleClick = (e: MouseEvent) => {
      const anchor = (e.target as HTMLElement).closest('a')
      const href = anchor?.getAttribute('href')
      if (!href?.startsWith('/') || anchor?.target || e.ctrlKey || e.metaKey) return
      e.preventDefault()
      navigate(href)
    }
    const handlePop = () => navigate(location.pathname)
    document.addEventListener('click', handleClick)
    window.addEventListener('popstate', handlePop)
    return () => {
      document.removeEventListener('click', handleClick)
      window.removeEventListener('popstate', handlePop)
    }
  }, [navigate])

  // Run Prism on initial mount
  useEffect(() => {
    if (typeof (window as any).Prism !== 'undefined') {
      ;(window as any).Prism.highlightAll()
    }
  }, [])

  const Page = pages[page]
  return Page ? <Page {...data} navigate={navigate} /> : null
}
