// examples/starter-svelte/src/lib/components/layout/NavGroup.svelte
<script lang="ts">
  import { ChevronRight, ExternalLink } from 'lucide-svelte'
  import { Collapsible } from 'bits-ui'
  import * as DropdownMenu from '$lib/components/ui/dropdown-menu'
  import * as Sidebar from '$lib/components/ui/sidebar'
  import { Badge } from '$lib/components/ui/badge'
  import type { NavGroup as NavGroupData } from './sidebar-data'

  let {
    group,
    activePath,
    navigate,
  }: {
    group: NavGroupData
    activePath: string
    navigate: (href: string) => void
  } = $props()

  const sidebar = Sidebar.useSidebar()

  function isActive(itemUrl: string, active: string): boolean {
    if (itemUrl === active) return true
    const itemBase = itemUrl.split('?')[0]
    const activeBase = active.split('?')[0]
    return itemBase === activeBase
  }

  function isGroupActive(items: NavGroupData['items'][number]['items'], active: string): boolean {
    if (!items) return false
    return items.some((sub) => isActive(sub.url, active))
  }
</script>

<Sidebar.Group>
  <Sidebar.GroupLabel>{group.title}</Sidebar.GroupLabel>
  <Sidebar.Menu>
    {#each group.items as item (item.url)}
      {#if item.items && item.items.length > 0}
        {#if sidebar.state === 'collapsed'}
          <!-- Collapsed: dropdown menu -->
          <Sidebar.MenuItem>
            <DropdownMenu.Root>
              <DropdownMenu.Trigger>
                {#snippet child({ props })}
                  <Sidebar.MenuButton
                    tooltipContent={item.title}
                    isActive={isGroupActive(item.items, activePath)}
                    {...props}
                  >
                    <item.icon />
                    <span>{item.title}</span>
                    <ChevronRight class="ml-auto" />
                  </Sidebar.MenuButton>
                {/snippet}
              </DropdownMenu.Trigger>
              <DropdownMenu.Content side="right" align="start" sideOffset={4}>
                <DropdownMenu.Label>{item.title}</DropdownMenu.Label>
                <DropdownMenu.Separator />
                {#each item.items as sub (sub.url)}
                  <DropdownMenu.Item onclick={() => navigate(sub.url)}>
                    <span>{sub.title}</span>
                  </DropdownMenu.Item>
                {/each}
              </DropdownMenu.Content>
            </DropdownMenu.Root>
          </Sidebar.MenuItem>
        {:else}
          <!-- Expanded: collapsible -->
          {@const childActive = isGroupActive(item.items, activePath)}
          <Collapsible.Root open={childActive} class="group/collapsible">
            <Sidebar.MenuItem>
              <Collapsible.Trigger>
                {#snippet child({ props })}
                  <Sidebar.MenuButton
                    tooltipContent={item.title}
                    isActive={childActive}
                    {...props}
                  >
                    <item.icon />
                    <span>{item.title}</span>
                    <ChevronRight class="ml-auto transition-transform duration-200 group-data-[state=open]/collapsible:rotate-90" />
                  </Sidebar.MenuButton>
                {/snippet}
              </Collapsible.Trigger>
              <Collapsible.Content>
                <Sidebar.MenuSub>
                  {#each item.items as sub (sub.url)}
                    <Sidebar.MenuSubItem>
                      <Sidebar.MenuSubButton
                        isActive={isActive(sub.url, activePath)}
                        onclick={(e: MouseEvent) => {
                          e.preventDefault()
                          navigate(sub.url)
                        }}
                      >
                        <span>{sub.title}</span>
                      </Sidebar.MenuSubButton>
                    </Sidebar.MenuSubItem>
                  {/each}
                </Sidebar.MenuSub>
              </Collapsible.Content>
            </Sidebar.MenuItem>
          </Collapsible.Root>
        {/if}
      {:else if item.external}
        <Sidebar.MenuItem>
          <Sidebar.MenuButton tooltipContent={item.title}>
            {#snippet child({ props })}
              <a href={item.url} target="_blank" rel="noopener noreferrer" {...props}>
                <item.icon />
                <span>{item.title}</span>
                <ExternalLink class="ml-auto h-3 w-3 text-muted-foreground" />
              </a>
            {/snippet}
          </Sidebar.MenuButton>
        </Sidebar.MenuItem>
      {:else}
        <Sidebar.MenuItem>
          <Sidebar.MenuButton
            tooltipContent={item.title}
            isActive={isActive(item.url, activePath)}
            onclick={(e: MouseEvent) => {
              e.preventDefault()
              navigate(item.url)
            }}
          >
            <item.icon />
            <span>{item.title}</span>
            {#if item.badge}
              <Badge
                variant="secondary"
                class="ml-auto text-[10px] px-1.5 py-0"
              >
                {item.badge}
              </Badge>
            {/if}
          </Sidebar.MenuButton>
        </Sidebar.MenuItem>
      {/if}
    {/each}
  </Sidebar.Menu>
</Sidebar.Group>

// playground/react-app/src/components/layout/nav-group.tsx
import { useState } from 'react'
import { ChevronRight, ExternalLink } from 'lucide-react'
import { Collapsible } from 'radix-ui'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import {
  SidebarGroup,
  SidebarGroupLabel,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarMenuSub,
  SidebarMenuSubButton,
  SidebarMenuSubItem,
  useSidebar,
} from '@/components/ui/sidebar'
import { Badge } from '@/components/ui/badge'
import type { NavGroup as NavGroupData } from './sidebar-data'

interface NavGroupProps {
  group: NavGroupData
  activePath: string
  navigate: (href: string) => void
}

function isActive(itemUrl: string, activePath: string): boolean {
  if (itemUrl === activePath) return true
  const itemBase = itemUrl.split('?')[0]
  const activeBase = activePath.split('?')[0]
  return itemBase === activeBase
}

function isGroupActive(
  items: NavGroupData['items'][number]['items'],
  activePath: string,
): boolean {
  if (!items) return false
  return items.some((sub) => isActive(sub.url, activePath))
}

export function NavGroup({ group, activePath, navigate }: NavGroupProps) {
  const { state } = useSidebar()

  return (
    <SidebarGroup>
      <SidebarGroupLabel>{group.title}</SidebarGroupLabel>
      <SidebarMenu>
        {group.items.map((item) =>
          item.items && item.items.length > 0 ? (
            state === 'collapsed' ? (
              <CollapsedNavItem
                key={item.title}
                item={item}
                activePath={activePath}
                navigate={navigate}
              />
            ) : (
              <CollapsibleNavItem
                key={item.title}
                item={item}
                activePath={activePath}
                navigate={navigate}
              />
            )
          ) : item.external ? (
            <SidebarMenuItem key={item.title}>
              <SidebarMenuButton tooltip={item.title} asChild>
                <a href={item.url} target="_blank" rel="noopener noreferrer">
                  <item.icon />
                  <span>{item.title}</span>
                  <ExternalLink className="ml-auto h-3 w-3 text-muted-foreground" />
                </a>
              </SidebarMenuButton>
            </SidebarMenuItem>
          ) : (
            <SidebarMenuItem key={item.title}>
              <SidebarMenuButton
                tooltip={item.title}
                isActive={isActive(item.url, activePath)}
                onClick={(e) => {
                  e.preventDefault()
                  navigate(item.url)
                }}
              >
                <item.icon />
                <span>{item.title}</span>
                {item.badge && (
                  <Badge
                    variant="secondary"
                    className="ml-auto text-[10px] px-1.5 py-0"
                  >
                    {item.badge}
                  </Badge>
                )}
              </SidebarMenuButton>
            </SidebarMenuItem>
          ),
        )}
      </SidebarMenu>
    </SidebarGroup>
  )
}

function CollapsibleNavItem({
  item,
  activePath,
  navigate,
}: {
  item: NavGroupData['items'][number]
  activePath: string
  navigate: (href: string) => void
}) {
  const childActive = isGroupActive(item.items, activePath)
  const [open, setOpen] = useState(childActive)

  return (
    <Collapsible.Root open={open} onOpenChange={setOpen} asChild>
      <SidebarMenuItem>
        <Collapsible.Trigger asChild>
          <SidebarMenuButton tooltip={item.title} isActive={childActive}>
            <item.icon />
            <span>{item.title}</span>
            <ChevronRight className="ml-auto transition-transform duration-200 group-data-[state=open]/collapsible:rotate-90" />
          </SidebarMenuButton>
        </Collapsible.Trigger>
        <Collapsible.Content>
          <SidebarMenuSub>
            {item.items!.map((sub) => (
              <SidebarMenuSubItem key={sub.title}>
                <SidebarMenuSubButton
                  isActive={isActive(sub.url, activePath)}
                  onClick={(e) => {
                    e.preventDefault()
                    navigate(sub.url)
                  }}
                >
                  <span>{sub.title}</span>
                </SidebarMenuSubButton>
              </SidebarMenuSubItem>
            ))}
          </SidebarMenuSub>
        </Collapsible.Content>
      </SidebarMenuItem>
    </Collapsible.Root>
  )
}

function CollapsedNavItem({
  item,
  activePath,
  navigate,
}: {
  item: NavGroupData['items'][number]
  activePath: string
  navigate: (href: string) => void
}) {
  const childActive = isGroupActive(item.items, activePath)

  return (
    <SidebarMenuItem>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <SidebarMenuButton
            tooltip={item.title}
            isActive={childActive}
          >
            <item.icon />
            <span>{item.title}</span>
            <ChevronRight className="ml-auto" />
          </SidebarMenuButton>
        </DropdownMenuTrigger>
        <DropdownMenuContent side="right" align="start" sideOffset={4}>
          <DropdownMenuLabel>{item.title}</DropdownMenuLabel>
          <DropdownMenuSeparator />
          {item.items!.map((sub) => (
            <DropdownMenuItem
              key={sub.title}
              onClick={() => navigate(sub.url)}
            >
              <span>{sub.title}</span>
            </DropdownMenuItem>
          ))}
        </DropdownMenuContent>
      </DropdownMenu>
    </SidebarMenuItem>
  )
}
