// packages/studio/frontend/src/components/tables/DataTable.tsx
import { cn } from '@/lib/utils'
import { Icon } from '@/components/Icon'
import { CellRenderer } from '@/components/tables/CellRenderer'
import { Filters } from '@/components/tables/Filters'
import { Pagination } from '@/components/tables/Pagination'
import type { TableSchema, PaginationMeta, ActionSchema } from '@/components/forms/types'

export interface DataTableProps {
  schema: TableSchema
  data: any[]
  meta: PaginationMeta
  search: string
  onSearchChange: (val: string) => void
  sort: string
  sortDirection: 'asc' | 'desc'
  onSortChange: (col: string) => void
  filters: Record<string, string>
  onFilterChange: (name: string, val: string) => void
  selectedIds: Set<number>
  onSelectionChange: (ids: Set<number>) => void
  page: number
  perPage: number
  onPageChange: (page: number) => void
  onPerPageChange: (perPage: number) => void
  onAction: (action: string, recordId: number) => void
  onBulkAction: (action: string, ids: number[]) => void
  onCreateClick: () => void
  loading?: boolean
}

export function DataTable({
  schema,
  data,
  meta,
  search,
  onSearchChange,
  sort,
  sortDirection,
  onSortChange,
  filters,
  onFilterChange,
  selectedIds,
  onSelectionChange,
  page,
  perPage,
  onPageChange,
  onPerPageChange,
  onAction,
  onBulkAction,
  onCreateClick,
  loading = false,
}: DataTableProps) {
  const visibleColumns = schema.columns.filter((c) => !c.hidden)
  const hasSelection = selectedIds.size > 0
  const allSelected = data.length > 0 && data.every((row) => selectedIds.has(row.id))

  function toggleSelectAll() {
    if (allSelected) {
      onSelectionChange(new Set())
    } else {
      const ids = new Set(data.map((row) => row.id as number))
      onSelectionChange(ids)
    }
  }

  function toggleSelectRow(id: number) {
    const next = new Set(selectedIds)
    if (next.has(id)) {
      next.delete(id)
    } else {
      next.add(id)
    }
    onSelectionChange(next)
  }

  function handleSortClick(columnName: string) {
    onSortChange(columnName)
  }

  function getAlignmentClass(alignment: string): string {
    switch (alignment) {
      case 'center': return 'text-center'
      case 'end': return 'text-right'
      default: return 'text-left'
    }
  }

  return (
    <div className="space-y-4">
      {/* Toolbar */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex flex-1 items-center gap-3">
          {/* Search */}
          {schema.searchable && (
            <div className="relative max-w-sm flex-1">
              <Icon name="search" className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <input
                type="text"
                value={search}
                onChange={(e) => onSearchChange(e.target.value)}
                placeholder="Search..."
                className={cn(
                  'flex h-10 w-full rounded-md border border-input bg-background pl-9 pr-3 py-2 text-sm ring-offset-background',
                  'placeholder:text-muted-foreground',
                  'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2',
                )}
              />
            </div>
          )}

          {/* Filters */}
          <Filters
            filters={schema.filters}
            values={filters}
            onChange={onFilterChange}
          />
        </div>

        {/* Header actions */}
        <div className="flex items-center gap-2">
          {schema.headerActions?.map((action: ActionSchema) => (
            <button
              key={action.name}
              type="button"
              onClick={() => onAction(action.name, 0)}
              className={cn(
                'inline-flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors',
                'border border-input bg-background hover:bg-accent hover:text-accent-foreground',
              )}
            >
              {action.icon && <Icon name={action.icon} className="h-4 w-4" />}
              {action.label}
            </button>
          ))}

          <button
            type="button"
            onClick={onCreateClick}
            className={cn(
              'inline-flex items-center gap-2 rounded-md px-4 py-2 text-sm font-medium transition-colors',
              'bg-primary text-primary-foreground hover:bg-primary/90',
            )}
          >
            <Icon name="plus" className="h-4 w-4" />
            Create
          </button>
        </div>
      </div>

      {/* Bulk actions bar */}
      {hasSelection && schema.bulkActions.length > 0 && (
        <div className="flex items-center gap-3 rounded-md border border-primary/20 bg-primary/5 px-4 py-2.5">
          <span className="text-sm font-medium">
            {selectedIds.size} selected
          </span>
          <div className="flex items-center gap-2">
            {schema.bulkActions.map((action) => (
              <button
                key={action.name}
                type="button"
                onClick={() => onBulkAction(action.name, Array.from(selectedIds))}
                className={cn(
                  'inline-flex items-center gap-1.5 rounded-md px-3 py-1.5 text-sm font-medium transition-colors',
                  action.color === 'danger'
                    ? 'bg-destructive text-destructive-foreground hover:bg-destructive/90'
                    : 'border border-input bg-background hover:bg-accent hover:text-accent-foreground',
                )}
              >
                {action.icon && <Icon name={action.icon} className="h-3.5 w-3.5" />}
                {action.label}
              </button>
            ))}
          </div>
          <button
            type="button"
            onClick={() => onSelectionChange(new Set())}
            className="ml-auto text-sm text-muted-foreground hover:text-foreground"
          >
            Deselect all
          </button>
        </div>
      )}

      {/* Table */}
      <div className="relative rounded-md border border-input">
        {loading && (
          <div className="absolute inset-0 z-10 flex items-center justify-center bg-background/60">
            <Icon name="loader-2" className="h-6 w-6 animate-spin text-muted-foreground" />
          </div>
        )}

        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-input bg-muted/50">
                {/* Checkbox column */}
                <th className="w-12 px-4 py-3">
                  <button
                    type="button"
                    role="checkbox"
                    aria-checked={allSelected}
                    onClick={toggleSelectAll}
                    className={cn(
                      'h-4 w-4 rounded-sm border border-primary ring-offset-background',
                      'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2',
                      allSelected && 'bg-primary text-primary-foreground',
                    )}
                  >
                    {allSelected && (
                      <span className="flex items-center justify-center">
                        <Icon name="check" className="h-3 w-3" />
                      </span>
                    )}
                  </button>
                </th>

                {visibleColumns.map((col) => (
                  <th
                    key={col.name}
                    className={cn(
                      'px-4 py-3 font-medium text-muted-foreground',
                      getAlignmentClass(col.alignment),
                      col.sortable && 'cursor-pointer select-none hover:text-foreground',
                    )}
                    style={col.width ? { width: col.width } : undefined}
                    onClick={() => col.sortable && handleSortClick(col.name)}
                  >
                    <div className={cn(
                      'inline-flex items-center gap-1',
                      col.alignment === 'center' && 'justify-center',
                      col.alignment === 'end' && 'justify-end',
                    )}>
                      <span>{col.label ?? col.name}</span>
                      {col.sortable && sort === col.name && (
                        <Icon
                          name={sortDirection === 'asc' ? 'arrow-up' : 'arrow-down'}
                          className="h-3.5 w-3.5"
                        />
                      )}
                      {col.sortable && sort !== col.name && (
                        <Icon name="arrow-up-down" className="h-3.5 w-3.5 opacity-30" />
                      )}
                    </div>
                  </th>
                ))}

                {/* Actions column */}
                {schema.actions.length > 0 && (
                  <th className="w-20 px-4 py-3 text-right font-medium text-muted-foreground">
                    Actions
                  </th>
                )}
              </tr>
            </thead>

            <tbody>
              {data.length === 0 ? (
                <tr>
                  <td
                    colSpan={visibleColumns.length + (schema.actions.length > 0 ? 2 : 1)}
                    className="px-4 py-16 text-center"
                  >
                    <div className="flex flex-col items-center gap-3">
                      <Icon
                        name={schema.emptyStateIcon || 'inbox'}
                        className="h-12 w-12 text-muted-foreground/50"
                      />
                      <div>
                        <h3 className="text-base font-semibold text-foreground">
                          {schema.emptyStateHeading}
                        </h3>
                        {schema.emptyStateDescription && (
                          <p className="mt-1 text-sm text-muted-foreground">
                            {schema.emptyStateDescription}
                          </p>
                        )}
                      </div>
                    </div>
                  </td>
                </tr>
              ) : (
                data.map((row) => {
                  const rowId = row.id as number
                  const isSelected = selectedIds.has(rowId)

                  return (
                    <tr
                      key={rowId}
                      className={cn(
                        'border-b border-input last:border-b-0 transition-colors',
                        isSelected && 'bg-primary/5',
                        schema.striped && 'even:bg-muted/30',
                        'hover:bg-muted/50',
                      )}
                    >
                      {/* Checkbox */}
                      <td className="w-12 px-4 py-3">
                        <button
                          type="button"
                          role="checkbox"
                          aria-checked={isSelected}
                          onClick={() => toggleSelectRow(rowId)}
                          className={cn(
                            'h-4 w-4 rounded-sm border border-primary ring-offset-background',
                            'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2',
                            isSelected && 'bg-primary text-primary-foreground',
                          )}
                        >
                          {isSelected && (
                            <span className="flex items-center justify-center">
                              <Icon name="check" className="h-3 w-3" />
                            </span>
                          )}
                        </button>
                      </td>

                      {visibleColumns.map((col) => (
                        <td
                          key={col.name}
                          className={cn(
                            'px-4 py-3',
                            getAlignmentClass(col.alignment),
                          )}
                        >
                          <CellRenderer
                            column={col}
                            value={row[col.name]}
                            record={row}
                          />
                        </td>
                      ))}

                      {/* Row actions */}
                      {schema.actions.length > 0 && (
                        <td className="px-4 py-3 text-right">
                          <div className="flex items-center justify-end gap-1">
                            {schema.actions.map((action) => (
                              <button
                                key={action.name}
                                type="button"
                                onClick={() => onAction(action.name, rowId)}
                                title={action.label}
                                className={cn(
                                  'inline-flex h-8 w-8 items-center justify-center rounded-md transition-colors',
                                  action.color === 'danger'
                                    ? 'text-destructive hover:bg-destructive/10'
                                    : 'text-muted-foreground hover:bg-muted hover:text-foreground',
                                )}
                              >
                                <Icon name={action.icon ?? 'more-horizontal'} className="h-4 w-4" />
                              </button>
                            ))}
                          </div>
                        </td>
                      )}
                    </tr>
                  )
                })
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Pagination */}
      {schema.paginated && meta.total > 0 && (
        <Pagination
          meta={meta}
          page={page}
          perPage={perPage}
          paginationPageOptions={schema.paginationPageOptions}
          onPageChange={onPageChange}
          onPerPageChange={onPerPageChange}
        />
      )}
    </div>
  )
}

// examples/starter-svelte/src/lib/components/DataTable.svelte
<script lang="ts" module>
  export interface Column<T> {
    id: string
    label: string
    hideable?: boolean
    className?: string
    cellClassName?: string
    sortKey?: string
    getValue?: (row: T) => any
  }

  export interface DataTableProps<T> {
    data: T[]
    columns: Column<T>[]
    loading?: boolean
    searchValue?: string
    onSearchChange?: (value: string) => void
    searchPlaceholder?: string
    page?: number
    perPage?: number
    totalItems?: number
    onPageChange?: (page: number) => void
    onPerPageChange?: (perPage: number) => void
    selectable?: boolean
    selectedIds?: Set<number | string>
    onSelectionChange?: (ids: Set<number | string>) => void
    getRowId?: (row: T) => number | string
    onSortChange?: (sortKey: string | null, sortDir: 'asc' | 'desc') => void
    emptyMessage?: string
  }
</script>

<script lang="ts" generics="T">
  import * as Table from '$lib/components/ui/table'
  import * as DropdownMenu from '$lib/components/ui/dropdown-menu'
  import { Button } from '$lib/components/ui/button'
  import { Input } from '$lib/components/ui/input'
  import { Skeleton } from '$lib/components/ui/skeleton'
  import {
    Search,
    ChevronLeft,
    ChevronRight,
    ChevronsLeft,
    ChevronsRight,
    ArrowUpDown,
    ArrowUp,
    ArrowDown,
    SlidersHorizontal,
  } from 'lucide-svelte'
  import type { Snippet } from 'svelte'

  let {
    data,
    columns,
    loading = false,
    searchValue,
    onSearchChange,
    searchPlaceholder = 'Search...',
    page: controlledPage,
    perPage: controlledPerPage,
    totalItems: controlledTotalItems,
    onPageChange,
    onPerPageChange,
    selectable = false,
    selectedIds: controlledSelectedIds,
    onSelectionChange,
    getRowId,
    onSortChange,
    toolbarLeft,
    toolbarRight,
    emptyMessage = 'No results found.',
    renderCell,
  }: DataTableProps<T> & {
    toolbarLeft?: Snippet
    toolbarRight?: Snippet
    renderCell?: Snippet<[{ column: Column<T>; row: T; index: number }]>
  } = $props()

  // Internal state
  let internalPage = $state(1)
  let internalPerPage = $state(10)
  let internalSelectedIds = $state(new Set<number | string>())
  let sortKey = $state<string | null>(null)
  let sortDir = $state<'asc' | 'desc'>('asc')
  let visibleColumns = $state(new Set(columns.map(c => c.id)))

  // Resolve controlled vs uncontrolled
  const page = $derived(controlledPage ?? internalPage)
  const perPage = $derived(controlledPerPage ?? internalPerPage)
  const selectedIds = $derived(controlledSelectedIds ?? internalSelectedIds)

  function setPage(v: number) {
    if (onPageChange) onPageChange(v)
    else internalPage = v
  }

  function setPerPage(v: number) {
    if (onPerPageChange) onPerPageChange(v)
    else internalPerPage = v
  }

  function setSelectedIds(next: Set<number | string>) {
    if (onSelectionChange) onSelectionChange(next)
    else internalSelectedIds = next
  }

  // Sorting
  const sorted = $derived.by(() => {
    if (onSortChange) return data
    if (!sortKey) return data
    const col = columns.find(c => c.sortKey === sortKey)
    if (!col?.getValue) return data
    const list = [...data]
    list.sort((a, b) => {
      const av = col.getValue!(a) ?? ''
      const bv = col.getValue!(b) ?? ''
      const cmp = av < bv ? -1 : av > bv ? 1 : 0
      return sortDir === 'asc' ? cmp : -cmp
    })
    return list
  })

  // Pagination
  const isServerPaginated = $derived(controlledTotalItems != null)
  const totalItems = $derived(controlledTotalItems ?? sorted.length)
  const totalPages = $derived(Math.max(1, Math.ceil(totalItems / perPage)))
  const paginated = $derived(isServerPaginated ? sorted : sorted.slice((page - 1) * perPage, page * perPage))

  // Clamp page
  $effect(() => {
    const maxPage = Math.max(1, Math.ceil(totalItems / perPage))
    if (page > maxPage) setPage(maxPage)
  })

  // Selection helpers
  const allPageSelected = $derived(
    paginated.length > 0 &&
    getRowId != null &&
    paginated.every(r => selectedIds.has(getRowId!(r)))
  )
  const somePageSelected = $derived(
    getRowId != null &&
    paginated.some(r => selectedIds.has(getRowId!(r))) &&
    !allPageSelected
  )

  function toggleAll(checked: boolean) {
    if (!getRowId) return
    const next = new Set(selectedIds)
    paginated.forEach(r => {
      const id = getRowId!(r)
      if (checked) next.add(id)
      else next.delete(id)
    })
    setSelectedIds(next)
  }

  function toggleOne(id: number | string) {
    const next = new Set(selectedIds)
    if (next.has(id)) next.delete(id)
    else next.add(id)
    setSelectedIds(next)
  }

  // Sort helpers
  function handleSort(key: string) {
    let newKey: string | null = key
    let newDir: 'asc' | 'desc' = 'asc'

    if (sortKey === key) {
      if (sortDir === 'asc') {
        newDir = 'desc'
      } else {
        newKey = null
        newDir = 'asc'
      }
    }

    sortKey = newKey
    sortDir = newDir
    onSortChange?.(newKey, newDir)
  }

  // Column visibility
  function isColVisible(id: string) { return visibleColumns.has(id) }
  function toggleColumn(id: string) {
    const next = new Set(visibleColumns)
    if (next.has(id)) next.delete(id)
    else next.add(id)
    visibleColumns = next
  }

  const hideableColumns = $derived(columns.filter(c => c.hideable))
  const visibleCols = $derived(columns.filter(c => isColVisible(c.id)))
  const totalColCount = $derived((selectable ? 1 : 0) + visibleCols.length)
</script>

<div class="space-y-4">
  <!-- Toolbar -->
  <div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
    <div class="flex flex-1 flex-wrap items-center gap-2">
      {#if onSearchChange}
        <div class="relative w-full sm:max-w-[250px]">
          <Search class="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-muted-foreground" />
          <Input
            placeholder={searchPlaceholder}
            value={searchValue ?? ''}
            oninput={(e: Event) => onSearchChange?.((e.target as HTMLInputElement).value)}
            class="h-8 pl-9 text-sm"
          />
        </div>
      {/if}
      {#if toolbarLeft}
        {@render toolbarLeft()}
      {/if}
    </div>

    <div class="flex items-center gap-2">
      {#if toolbarRight}
        {@render toolbarRight()}
      {/if}
      {#if hideableColumns.length > 0}
        <DropdownMenu.Root>
          <DropdownMenu.Trigger>
            {#snippet child({ props })}
              <Button variant="outline" size="sm" class="ml-auto h-8 gap-1.5" {...props}>
                <SlidersHorizontal class="size-3.5" />
                View
              </Button>
            {/snippet}
          </DropdownMenu.Trigger>
          <DropdownMenu.Content align="end" class="w-40">
            <DropdownMenu.Label>Toggle columns</DropdownMenu.Label>
            <DropdownMenu.Separator />
            {#each hideableColumns as col (col.id)}
              <DropdownMenu.CheckboxItem
                checked={isColVisible(col.id)}
                onCheckedChange={() => toggleColumn(col.id)}
              >
                {col.label}
              </DropdownMenu.CheckboxItem>
            {/each}
          </DropdownMenu.Content>
        </DropdownMenu.Root>
      {/if}
    </div>
  </div>

  <!-- Table -->
  <div class="rounded-md border">
    <Table.Root>
      <Table.Header>
        <Table.Row>
          {#if selectable}
            <Table.Head class="w-10">
              <button
                type="button"
                role="checkbox"
                aria-checked={somePageSelected ? 'mixed' : allPageSelected}
                onclick={() => toggleAll(!allPageSelected)}
                class="inline-flex size-4 shrink-0 items-center justify-center rounded-[4px] border border-input transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring {allPageSelected || somePageSelected ? 'border-primary bg-primary text-primary-foreground' : 'bg-background'}"
              >
                {#if allPageSelected}
                  <svg width="10" height="10" viewBox="0 0 10 10" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M1.5 5.5L4 8L8.5 2" /></svg>
                {:else if somePageSelected}
                  <svg width="10" height="10" viewBox="0 0 10 10" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"><path d="M2 5H8" /></svg>
                {/if}
              </button>
            </Table.Head>
          {/if}
          {#each visibleCols as col (col.id)}
            <Table.Head class={col.className}>
              {#if col.sortKey}
                <button
                  type="button"
                  class="inline-flex items-center text-sm font-medium hover:text-foreground"
                  onclick={() => handleSort(col.sortKey!)}
                >
                  {col.label}
                  {#if sortKey !== col.sortKey}
                    <ArrowUpDown class="ml-1 size-3 text-muted-foreground/50" />
                  {:else if sortDir === 'asc'}
                    <ArrowUp class="ml-1 size-3" />
                  {:else}
                    <ArrowDown class="ml-1 size-3" />
                  {/if}
                </button>
              {:else}
                {col.label}
              {/if}
            </Table.Head>
          {/each}
        </Table.Row>
      </Table.Header>

      <Table.Body>
        {#if loading}
          {#each Array(perPage) as _, i}
            <Table.Row>
              {#if selectable}
                <Table.Cell><Skeleton class="size-4 rounded" /></Table.Cell>
              {/if}
              {#each visibleCols as col (col.id)}
                <Table.Cell class={col.cellClassName}><Skeleton class="h-4 w-24" /></Table.Cell>
              {/each}
            </Table.Row>
          {/each}
        {:else}
          {#each paginated as row, rowIndex}
            {@const rowId = getRowId?.(row)}
            <Table.Row data-state={rowId != null && selectedIds.has(rowId) ? 'selected' : undefined}>
              {#if selectable && rowId != null}
                <Table.Cell>
                  <button
                    type="button"
                    role="checkbox"
                    aria-checked={selectedIds.has(rowId)}
                    onclick={() => toggleOne(rowId)}
                    class="inline-flex size-4 shrink-0 items-center justify-center rounded-[4px] border border-input transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring {selectedIds.has(rowId) ? 'border-primary bg-primary text-primary-foreground' : 'bg-background'}"
                  >
                    {#if selectedIds.has(rowId)}
                      <svg width="10" height="10" viewBox="0 0 10 10" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M1.5 5.5L4 8L8.5 2" /></svg>
                    {/if}
                  </button>
                </Table.Cell>
              {/if}
              {#each visibleCols as col (col.id)}
                <Table.Cell class={col.cellClassName}>
                  {#if renderCell}
                    {@render renderCell({ column: col, row, index: (page - 1) * perPage + rowIndex })}
                  {/if}
                </Table.Cell>
              {/each}
            </Table.Row>
          {/each}
          {#if paginated.length === 0}
            <Table.Row>
              <Table.Cell colspan={totalColCount} class="h-32 text-center">
                <p class="text-sm text-muted-foreground">{emptyMessage}</p>
              </Table.Cell>
            </Table.Row>
          {/if}
        {/if}
      </Table.Body>
    </Table.Root>
  </div>

  <!-- Pagination footer -->
  <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
    <p class="text-sm text-muted-foreground">
      {#if selectable}
        {selectedIds.size} of {totalItems} row(s) selected.
      {:else}
        {totalItems} row(s) total.
      {/if}
    </p>

    <div class="flex flex-wrap items-center gap-4 sm:gap-6">
      <div class="flex items-center gap-2">
        <span class="text-sm text-muted-foreground whitespace-nowrap">Rows per page</span>
        <select
          value={perPage}
          onchange={(e: Event) => {
            setPerPage(Number((e.target as HTMLSelectElement).value))
            setPage(1)
          }}
          class="h-8 w-16 rounded-md border border-input bg-background px-2 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
        >
          <option value={10}>10</option>
          <option value={20}>20</option>
          <option value={50}>50</option>
        </select>
      </div>

      <span class="text-sm text-muted-foreground whitespace-nowrap">
        Page {page} of {totalPages}
      </span>

      <div class="flex items-center gap-1">
        <Button variant="outline" size="icon" class="size-8" disabled={page === 1} onclick={() => setPage(1)}>
          <ChevronsLeft class="size-4" />
          <span class="sr-only">First page</span>
        </Button>
        <Button variant="outline" size="icon" class="size-8" disabled={page === 1} onclick={() => setPage(page - 1)}>
          <ChevronLeft class="size-4" />
          <span class="sr-only">Previous page</span>
        </Button>
        <Button variant="outline" size="icon" class="size-8" disabled={page === totalPages} onclick={() => setPage(page + 1)}>
          <ChevronRight class="size-4" />
          <span class="sr-only">Next page</span>
        </Button>
        <Button variant="outline" size="icon" class="size-8" disabled={page === totalPages} onclick={() => setPage(totalPages)}>
          <ChevronsRight class="size-4" />
          <span class="sr-only">Last page</span>
        </Button>
      </div>
    </div>
  </div>
</div>
