// examples/starter-svelte/src/pages/Login.svelte
<script lang="ts">
  import { post } from '$lib/api'
  import { Button } from '$lib/components/ui/button'
  import { Input } from '$lib/components/ui/input'
  import { Label } from '$lib/components/ui/label'

  let {
    appName = 'Mantiq',
    navigate,
  }: {
    appName?: string
    navigate: (href: string) => void
    [key: string]: any
  } = $props()

  let email = $state('admin@example.com')
  let password = $state('password')
  let error = $state('')
  let loading = $state(false)

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault()
    error = ''
    loading = true
    const { ok, data } = await post('/login', { email, password })
    if (ok) navigate('/dashboard')
    else error = data?.error ?? 'Invalid email or password. Please try again.'
    loading = false
  }
</script>

<div class="min-h-screen flex bg-background">
  <!-- Left brand panel -->
  <div class="hidden lg:flex lg:w-[45%] bg-foreground text-background flex-col justify-between p-10">
    <div class="flex items-center gap-3">
      <div class="flex h-8 w-8 items-center justify-center rounded bg-background text-foreground text-xs font-bold">
        M
      </div>
      <span class="text-lg font-semibold tracking-tight">{appName}</span>
    </div>

    <div>
      <blockquote class="text-2xl font-medium leading-snug tracking-tight">
        "The framework that gets out of your way."
      </blockquote>
    </div>

    <p class="text-sm text-background/50">
      &copy; {new Date().getFullYear()} {appName}. All rights reserved.
    </p>
  </div>

  <!-- Right form panel -->
  <div class="flex flex-1 flex-col items-center justify-center px-6 py-12">
    <!-- Mobile-only logo -->
    <div class="mb-10 flex items-center gap-3 lg:hidden">
      <div class="flex h-8 w-8 items-center justify-center rounded bg-foreground text-background text-xs font-bold">
        M
      </div>
      <span class="text-lg font-semibold tracking-tight">{appName}</span>
    </div>

    <div class="w-full max-w-sm">
      <div class="mb-8">
        <h1 class="text-2xl font-semibold tracking-tight">Sign in</h1>
        <p class="mt-2 text-sm text-muted-foreground">
          Enter your credentials to continue
        </p>
      </div>

      {#if error}
        <div class="mb-6 rounded-md border border-destructive px-4 py-3 text-sm text-destructive">
          {error}
        </div>
      {/if}

      <form onsubmit={handleSubmit} class="space-y-4">
        <div class="space-y-2">
          <Label for="email">Email</Label>
          <Input
            id="email"
            type="email"
            bind:value={email}
            required
            placeholder="admin@example.com"
            autocomplete="email"
          />
        </div>
        <div class="space-y-2">
          <Label for="password">Password</Label>
          <Input
            id="password"
            type="password"
            bind:value={password}
            required
            placeholder="Enter your password"
            autocomplete="current-password"
          />
        </div>
        <Button type="submit" class="w-full" disabled={loading}>
          {loading ? 'Signing in...' : 'Sign in'}
        </Button>
      </form>

      <p class="mt-6 text-center text-sm text-muted-foreground">
        Don't have an account?{' '}
        <button
          type="button"
          class="font-medium text-foreground underline underline-offset-4"
          onclick={() => navigate('/register')}
        >
          Register
        </button>
      </p>
    </div>
  </div>
</div>

// examples/kit-react/src/pages/Login.tsx
import { useState } from 'react'
import { post } from '../lib/api.ts'

interface LoginProps {
  appName?: string
  navigate: (href: string) => void
  [key: string]: any
}

export default function Login({ appName = 'examples/kit-react', navigate }: LoginProps) {
  const [email, setEmail] = useState('admin@example.com')
  const [password, setPassword] = useState('password')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault(); setError(''); setLoading(true)
    const { ok, data } = await post('/login', { email, password })
    if (ok) navigate('/dashboard')
    else setError(data?.error ?? 'Login failed')
    setLoading(false)
  }

  return (
    <div className="min-h-screen bg-gray-950 flex">
      <div className="hidden lg:flex lg:w-1/2 bg-gradient-to-br from-indigo-950 via-gray-950 to-gray-950 items-center justify-center p-16 relative overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_40%,rgba(99,102,241,0.08),transparent_60%)]" />
        <div className="relative space-y-6 max-w-md">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-xl bg-indigo-600/20 border border-indigo-500/30 flex items-center justify-center">
              <svg className="w-6 h-6 text-indigo-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
            </div>
            <span className="text-2xl font-bold text-white">{appName}</span>
          </div>
          <h2 className="text-4xl font-bold text-white leading-tight">Build something<br />amazing.</h2>
          <p className="text-gray-400 text-lg leading-relaxed">
            Session auth, encrypted cookies, CSRF protection — all wired up and ready to go.
          </p>
        </div>
      </div>
      <div className="flex-1 flex items-center justify-center p-8">
        <div className="bg-gray-900 rounded-xl border border-gray-800 w-full max-w-md p-8 space-y-6">
          <div>
            <h1 className="text-xl font-bold text-white">Welcome back</h1>
            <p className="text-sm text-gray-500 mt-1">Sign in to your account</p>
          </div>
          {error && <div className="bg-red-500/10 border border-red-500/30 text-red-400 rounded-lg px-3.5 py-2.5 text-sm">{error}</div>}
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="space-y-1">
              <label className="block text-sm font-medium text-gray-400">Email</label>
              <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required
                className="w-full bg-gray-900 border border-gray-800 rounded-lg px-3.5 py-2.5 text-sm text-gray-100 placeholder-gray-600 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/30 transition-all" />
            </div>
            <div className="space-y-1">
              <label className="block text-sm font-medium text-gray-400">Password</label>
              <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required
                className="w-full bg-gray-900 border border-gray-800 rounded-lg px-3.5 py-2.5 text-sm text-gray-100 placeholder-gray-600 focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/30 transition-all" />
            </div>
            <button type="submit" disabled={loading}
              className="w-full bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed text-white font-semibold text-sm py-2.5 rounded-lg transition-colors">
              Sign in
            </button>
          </form>
          <p className="text-sm text-gray-500 text-center">
            Don't have an account? <a href="/register" className="text-indigo-400 hover:text-indigo-300">Register</a>
          </p>
        </div>
      </div>
    </div>
  )
}
