// playground/react-app/src/components/layout/main.tsx
import { cn } from '@/lib/utils'

interface MainProps extends React.HTMLAttributes<HTMLElement> {
  fixed?: boolean
}

export function Main({ fixed, className, children, ...props }: MainProps) {
  return (
    <main
      className={cn(
        'peer-[.header-fixed]/header:mt-16',
        fixed && 'flex flex-grow flex-col overflow-hidden',
        className,
      )}
      {...props}
    >
      <div className="px-4 py-6 lg:px-6">
        {children}
      </div>
    </main>
  )
}

// examples/starter-svelte/src/lib/components/layout/Main.svelte
<script lang="ts">
  import { cn } from '$lib/utils'
  import type { Snippet } from 'svelte'

  let {
    fixed = false,
    class: className,
    children,
  }: {
    fixed?: boolean
    class?: string
    children: Snippet
  } = $props()
</script>

<main
  class={cn(
    'peer-[.header-fixed]/header:mt-16',
    fixed && 'flex flex-grow flex-col overflow-hidden',
    className,
  )}
>
  <div class="px-4 py-6 lg:px-6">
    {@render children()}
  </div>
</main>
