// examples/starter-svelte/src/lib/components/layout/Main.svelte
<script lang="ts">
  import { cn } from '$lib/utils'
  import type { Snippet } from 'svelte'

  let {
    fixed = false,
    class: className,
    children,
  }: {
    fixed?: boolean
    class?: string
    children: Snippet
  } = $props()
</script>

<main
  class={cn(
    'peer-[.header-fixed]/header:mt-16',
    fixed && 'flex flex-grow flex-col overflow-hidden',
    className,
  )}
>
  <div class="px-4 py-6 lg:px-6">
    {@render children()}
  </div>
</main>

// examples/starter-vue/src/components/layout/Main.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'

const props = defineProps<{
  fixed?: boolean
  class?: string
}>()
</script>

<template>
  <main
    :class="cn(
      'peer-[.header-fixed]/header:mt-16',
      fixed && 'flex flex-grow flex-col overflow-hidden',
      props.class,
    )"
  >
    <div class="px-4 py-6 lg:px-6">
      <slot />
    </div>
  </main>
</template>
