// examples/starter-svelte/src/lib/components/layout/TopNav.svelte
<script lang="ts">
  import { cn } from '$lib/utils'
  import * as DropdownMenu from '$lib/components/ui/dropdown-menu'
  import { Button } from '$lib/components/ui/button'
  import { Menu } from 'lucide-svelte'

  interface TopNavLink {
    title: string
    href: string
    isActive?: boolean
    disabled?: boolean
  }

  let {
    links,
    onLinkClick,
    class: className,
  }: {
    links: TopNavLink[]
    onLinkClick?: (href: string) => void
    class?: string
  } = $props()

  function handleClick(e: MouseEvent, href: string) {
    if (onLinkClick) {
      e.preventDefault()
      onLinkClick(href)
    }
  }
</script>

<!-- Desktop navigation -->
<nav
  class={cn(
    'hidden items-center gap-4 md:flex lg:gap-6',
    className,
  )}
>
  {#each links as link (link.href)}
    <a
      href={link.href}
      onclick={(e: MouseEvent) => handleClick(e, link.href)}
      class={cn(
        'text-sm font-medium transition-colors hover:text-primary',
        link.isActive ? 'text-foreground' : 'text-muted-foreground',
        link.disabled && 'pointer-events-none opacity-50',
      )}
    >
      {link.title}
    </a>
  {/each}
</nav>

<!-- Mobile navigation -->
<div class="md:hidden">
  <DropdownMenu.Root>
    <DropdownMenu.Trigger>
      {#snippet child({ props })}
        <Button variant="outline" size="icon" class="h-8 w-8" {...props}>
          <Menu class="h-4 w-4" />
          <span class="sr-only">Toggle navigation</span>
        </Button>
      {/snippet}
    </DropdownMenu.Trigger>
    <DropdownMenu.Content align="start">
      {#each links as link (link.href)}
        <DropdownMenu.Item
          disabled={link.disabled}
          onclick={(e: MouseEvent) => {
            if (onLinkClick) {
              onLinkClick(link.href)
            }
          }}
          class={cn(!link.isActive && 'text-muted-foreground')}
        >
          {link.title}
        </DropdownMenu.Item>
      {/each}
    </DropdownMenu.Content>
  </DropdownMenu.Root>
</div>

// examples/starter-vue/src/components/layout/TopNav.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { Button } from '@/components/ui/button'
import { Menu } from 'lucide-vue-next'

export interface TopNavLink {
  title: string
  href: string
  isActive?: boolean
  disabled?: boolean
}

const props = defineProps<{
  links: TopNavLink[]
  class?: string
}>()

const emit = defineEmits<{
  linkClick: [href: string]
}>()

function handleClick(e: MouseEvent, href: string) {
  e.preventDefault()
  emit('linkClick', href)
}
</script>

<template>
  <!-- Desktop navigation -->
  <nav
    :class="cn('hidden items-center gap-4 md:flex lg:gap-6', props.class)"
  >
    <a
      v-for="link in links"
      :key="link.href"
      :href="link.href"
      :class="cn(
        'text-sm font-medium transition-colors hover:text-primary',
        link.isActive ? 'text-foreground' : 'text-muted-foreground',
        link.disabled && 'pointer-events-none opacity-50',
      )"
      @click="handleClick($event, link.href)"
    >
      {{ link.title }}
    </a>
  </nav>

  <!-- Mobile navigation -->
  <div class="md:hidden">
    <DropdownMenu>
      <DropdownMenuTrigger as-child>
        <Button variant="outline" size="icon" class="h-8 w-8">
          <Menu class="h-4 w-4" />
          <span class="sr-only">Toggle navigation</span>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="start">
        <DropdownMenuItem
          v-for="link in links"
          :key="link.href"
          :disabled="link.disabled"
          @select="emit('linkClick', link.href)"
        >
          <span :class="cn(!link.isActive && 'text-muted-foreground')">
            {{ link.title }}
          </span>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  </div>
</template>
