// playground/react-app/src/App.tsx
import { useState, useCallback, useEffect } from 'react'

declare global { interface Window { __MANTIQ_DATA__?: Record<string, any> } }

interface MantiqAppProps {
  pages: Record<string, React.ComponentType<any>>
  initialData?: Record<string, any>
}

function initTheme() {
  if (typeof window === 'undefined') return
  const theme = localStorage.getItem('theme') ||
    (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light')
  document.documentElement.classList.toggle('dark', theme === 'dark')
}

initTheme()

export function MantiqApp({ pages, initialData }: MantiqAppProps) {
  const windowData = typeof window !== 'undefined' ? window.__MANTIQ_DATA__ : {}
  const initial = initialData ?? windowData
  const [page, setPage] = useState<string>(initial._page ?? 'Login')
  const [data, setData] = useState<Record<string, any>>(initial)

  const navigate = useCallback(async (href: string) => {
    const res = await fetch(href, {
      headers: { 'X-Mantiq': 'true', Accept: 'application/json' },
    })
    if (res.status === 401 || res.status === 419) {
      window.location.href = '/login'
      return
    }
    const ct = res.headers.get('content-type') ?? ''
    if (!ct.includes('application/json')) {
      window.location.href = href
      return
    }
    const newData = await res.json()
    setPage(newData._page)
    setData(newData)
    history.pushState(null, '', newData._url)
  }, [])

  useEffect(() => {
    const handleClick = (e: MouseEvent) => {
      const anchor = (e.target as HTMLElement).closest('a')
      const href = anchor?.getAttribute('href')
      if (!href?.startsWith('/') || anchor?.target || e.ctrlKey || e.metaKey) return
      // Only intercept known SPA routes — let other links navigate normally
      const spaRoutes = ['/login', '/register', '/dashboard', '/users', '/account/profile', '/account/security', '/account/preferences']
      if (!spaRoutes.some(r => href === r || href.startsWith(r + '?'))) return
      e.preventDefault()
      navigate(href)
    }
    const handlePop = () => navigate(location.pathname)
    document.addEventListener('click', handleClick)
    window.addEventListener('popstate', handlePop)
    return () => {
      document.removeEventListener('click', handleClick)
      window.removeEventListener('popstate', handlePop)
    }
  }, [navigate])

  const Page = pages[page]
  return Page ? <Page {...data} navigate={navigate} /> : null
}

// examples/starter-svelte/src/App.svelte
<script lang="ts">
  import { onMount, onDestroy, setContext } from 'svelte'

  let {
    pages = {},
    initialData = {},
  }: {
    pages?: Record<string, any>
    initialData?: Record<string, any>
  } = $props()

  const windowData = typeof window !== 'undefined' ? (window as any).__MANTIQ_DATA__ : {}
  const bootstrapData = initialData ?? windowData

  let currentPage = $state<string>(bootstrapData._page ?? 'Login')
  let pageData = $state<Record<string, any>>(bootstrapData)

  const PageComponent = $derived(pages[currentPage] ?? null)

  // Initialize theme immediately to prevent flash
  if (typeof window !== 'undefined') {
    const theme = localStorage.getItem('theme') ||
      (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light')
    document.documentElement.classList.toggle('dark', theme === 'dark')
  }

  async function navigate(href: string) {
    const res = await fetch(href, {
      headers: { 'X-Mantiq': 'true', Accept: 'application/json' },
    })

    // Handle 401/419 — session expired
    if (res.status === 401 || res.status === 419) {
      window.location.href = '/login'
      return
    }

    const newData = await res.json()
    currentPage = newData._page
    pageData = newData
    history.pushState(null, '', newData._url)
  }

  setContext('navigate', navigate)

  const spaRoutes = [
    '/login', '/register', '/dashboard', '/users',
    '/account/profile', '/account/security', '/account/preferences',
  ]

  function handleClick(e: MouseEvent) {
    const anchor = (e.target as HTMLElement).closest('a')
    const href = anchor?.getAttribute('href')
    if (!href?.startsWith('/') || anchor?.target || e.ctrlKey || e.metaKey) return
    if (!spaRoutes.some(r => href === r || href.startsWith(r + '?'))) return
    e.preventDefault()
    navigate(href)
  }

  function handlePop() { navigate(location.pathname) }

  onMount(() => {
    document.addEventListener('click', handleClick)
    window.addEventListener('popstate', handlePop)
  })

  onDestroy(() => {
    if (typeof window !== 'undefined') {
      document.removeEventListener('click', handleClick)
      window.removeEventListener('popstate', handlePop)
    }
  })
</script>

{#if PageComponent}
  <PageComponent {...pageData} {navigate} />
{/if}
