// examples/starter-svelte/src/pages/account/profile.svelte
<script lang="ts">
  import AccountLayout from './layout.svelte'
  import { Button } from '$lib/components/ui/button'
  import { Input } from '$lib/components/ui/input'
  import { Label } from '$lib/components/ui/label'

  let {
    appName,
    currentUser = null,
    navigate,
  }: {
    appName?: string
    currentUser?: { id: number; name: string; email: string } | null
    navigate: (href: string) => void
    [key: string]: any
  } = $props()

  let name = $state(currentUser?.name ?? '')
  let email = $state(currentUser?.email ?? '')
  let saving = $state(false)
  let saved = $state(false)

  async function handleSave(e: SubmitEvent) {
    e.preventDefault()
    saving = true
    await new Promise(r => setTimeout(r, 500))
    saving = false
    saved = true
    setTimeout(() => saved = false, 3000)
  }
</script>

<AccountLayout {appName} {currentUser} {navigate} activePath="/account/profile">
  <div class="space-y-6">
    <div>
      <h3 class="text-lg font-medium">Profile</h3>
      <p class="text-sm text-muted-foreground">
        This is how others will see you on the site.
      </p>
    </div>
    <form onsubmit={handleSave} class="space-y-6">
      <div class="space-y-2">
        <Label for="name">Name</Label>
        <Input id="name" bind:value={name} />
        <p class="text-xs text-muted-foreground">
          This is your public display name.
        </p>
      </div>
      <div class="space-y-2">
        <Label for="email">Email</Label>
        <Input id="email" type="email" bind:value={email} />
        <p class="text-xs text-muted-foreground">
          Your email address is used for notifications.
        </p>
      </div>
      <div class="flex items-center gap-3">
        <Button type="submit" disabled={saving}>
          {saving ? 'Saving...' : 'Update profile'}
        </Button>
        {#if saved}
          <span class="text-sm text-muted-foreground">Saved.</span>
        {/if}
      </div>
    </form>
  </div>
</AccountLayout>

// studio-test/src/pages/account/profile.tsx
import { useState } from 'react'
import { post } from '../../lib/api.ts'
import { AccountLayout } from './layout.tsx'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

interface ProfileProps {
  appName?: string
  currentUser?: { id: number; name: string; email: string } | null
  navigate: (href: string) => void
  [key: string]: any
}

export default function Profile({ appName, currentUser, navigate }: ProfileProps) {
  const [name, setName] = useState(currentUser?.name ?? '')
  const [email, setEmail] = useState(currentUser?.email ?? '')
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault()
    setSaving(true)
    // await post('/api/account/profile', { name, email })
    await new Promise(r => setTimeout(r, 500))
    setSaving(false)
    setSaved(true)
    setTimeout(() => setSaved(false), 3000)
  }

  return (
    <AccountLayout appName={appName} currentUser={currentUser} navigate={navigate} activePath="/account/profile">
      <div className="space-y-6">
        <div>
          <h3 className="text-lg font-medium">Profile</h3>
          <p className="text-sm text-muted-foreground">
            This is how others will see you on the site.
          </p>
        </div>
        <form onSubmit={handleSave} className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="name">Name</Label>
            <Input id="name" value={name} onChange={e => setName(e.target.value)} />
            <p className="text-xs text-muted-foreground">
              This is your public display name.
            </p>
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" type="email" value={email} onChange={e => setEmail(e.target.value)} />
            <p className="text-xs text-muted-foreground">
              Your email address is used for notifications.
            </p>
          </div>
          <div className="flex items-center gap-3">
            <Button type="submit" disabled={saving}>
              {saving ? 'Saving...' : 'Update profile'}
            </Button>
            {saved && <span className="text-sm text-muted-foreground">Saved.</span>}
          </div>
        </form>
      </div>
    </AccountLayout>
  )
}
